name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - save_cache:
            key: dependency-cache
            paths:
              - ./node_modules
              - ./.next/cache
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18' # Устанавливаем Node.js 18.18 или новее

      - name: Install dependencies
        run: npm install

      - name: Build Next.js and export static site
        run: npm run deploy

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
